import{a as b,S as v,i as a}from"./assets/vendor-DirGshhi.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))d(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&d(c)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function d(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const q="55700970-bcda54bd417603eeff8d80436",S="https://pixabay.com/api/";async function u(r,e){try{return(await b.get(S,{params:{key:q,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15}})).data}catch{throw new Error("Pixabay request failed")}}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),h=document.querySelector(".load-more"),E=new v(".gallery a",{captionsData:"alt",captionDelay:250});function y(r){const e=r.map(o=>`
    <li class="gallery-item">
      <a href="${o.largeImageURL}">
        <img src="${o.webformatURL}" alt="${o.tags}" />
      </a>
      <div class="info">
        <p>Likes: ${o.likes}</p>
        <p>Views: ${o.views}</p>
        <p>Comments: ${o.comments}</p>
        <p>Downloads: ${o.downloads}</p>
      </div>
    </li>
  `).join("");f.insertAdjacentHTML("beforeend",e),E.refresh()}function B(){f.innerHTML=""}function p(){m.classList.remove("hidden")}function g(){m.classList.add("hidden")}function L(){h.classList.remove("hidden")}function w(){h.classList.add("hidden")}const $=document.querySelector(".form"),M=document.querySelector(".load-more");let i="",n=1,l=0;$.addEventListener("submit",async r=>{if(r.preventDefault(),i=r.target.elements["search-text"].value.trim(),!i){a.warning({title:"Warning",message:"Please enter a search term!"});return}n=1,B(),w(),p();try{const e=await u(i,n);if(l=e.totalHits,e.hits.length===0){a.info({message:"No images found!"});return}y(e.hits),l>n*15?L():a.info({message:"We're sorry, but you've reached the end of search results."})}catch(e){console.log(e),a.error({message:"Error fetching images!"})}finally{g()}});M.addEventListener("click",async()=>{n+=1,w(),p();try{const r=await u(i,n);y(r.hits);const{height:e}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"}),n*15>=l?a.info({message:"We're sorry, but you've reached the end of search results."}):L()}catch(r){console.error(r),a.error({message:"Error fetching more images!"})}finally{g()}});
//# sourceMappingURL=index.js.map
